//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCpartStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntelCPU
    {
        public int Id { get; set; }
        public string Image { get; set; }
        public string Core { get; set; }
        public string Model { get; set; }
        public string Speed { get; set; }
        public string Socket { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
    }
}
